### ISSUE TITLE
OnNetworkReceive never called for standalone clients

### ISSUE THREAD

**Issue by Saishy** [RevenantX/LiteNetLib#116]
Thanks again for the lib and sorry to annoy. When I'm testing with a listen server (both server and client) everything works fine, but when I'm only a client the OnNetworkReceive is never called, also debugged and there are no packets in the poll.

It connects normally, I receive latency updates normally, the only thing that does not work is any messages that would be received by OnNetworkReceive.

You can check my repo here: https://github.com/Saishy/TinyBirdNet-Unity

**Comment by RevenantX** [comment]
@Saishy as i see you fixed this?

**Comment by Saishy** [comment]
No I didn't?

**Comment by RevenantX** [comment]
@Saishy can you provide minimal example of problem?

**Comment by Saishy** [comment]
Uhm that would be hard...

**Comment by RevenantX** [comment]
@Saishy I do not quite understand your problem. Maybe this error in your code?

**Comment by Saishy** [comment]
I will try to update the lib and get back to you.

**Comment by Saishy** [comment]
I was able to get the issue, it happened as soon as I did the same thing I did in my API. (trying to send something to a peer on the onpeerconnected.

But in this case the bug also happened to me on listen server?
No error log, networkreceive is just never called.

[LiteNetLib_MinimalBugSaishy.zip](https://github.com/RevenantX/LiteNetLib/files/1562919/LiteNetLib_MinimalBugSaishy.zip)

**Comment by RevenantX** [comment]
@Saishy your `NetClient.Update` is wrong.
fixed:
```csharp
        if(_netClient != null)
            _netClient.PollEvents();
        if (bStart && _netClient != null && _netClient.IsRunning) {
```

**Comment by Saishy** [comment]
Wait, so only the client don't need to check for IsRunning?

(Also yeah, the bStart was a slip, oops)

**Comment by RevenantX** [comment]
@Saishy you can check `IsRunning` for pollevents but this no makes sense)

**Comment by Saishy** [comment]
Hmm, I'm still not able to find out why my clients are not receiving OnNetworkReceive messages...
The Server always receive it fine, and if the client is a listen server it also works on the client...

Other kinds of messages like latency are received normally.

**Comment by RevenantX** [comment]
@Saishy ok. I debugged this for you.
Remove
`[Conditional("DEBUG")]` from TinyLogger...
Seems that this is Unity bug. And conditional attribute applied incorrectly in standalone build.

**Comment by Saishy** [comment]
Wtf rly... Many thanks ;^;
